### ISSUE TITLE
Loader has been detatched from Blogs on Main Page

### ISSUE THREAD

**Issue by mrigankpawagi** [databasedIISc/databasediisc.github.io#4]
Fetching RSS feed from Blogger sometimes fails due to CORB. This prevents the loader from fading out. As a temporary fix, I have detached the fetch for blog from the loading sequence (check `tryUnload` in `js/index.js`). This is not noticeable at the moment because airtable usually returns much after blogger, but we might want to consider fixing this. 

This issue is flaky and would either need some fixes in our fetching (like fetching as JSON and not a Js script, and figuring out the right headers) or a shift to the Blogger API.

**Comment by sharaths21312** [comment]
Switching to the API would certainly be convenient, you need to create an API key for it first (I don't have access)

**Comment by mrigankpawagi** [comment]
Perfect! We will explore the blogger API later.
